### PR TITLE
New localization capability

### PR DESCRIPTION
**Pull request by mwd3**
Hello,

This is Mark Dudley. I sent a couple emails to Johannes Meyer about my work with localization and this is the final project. I added a modified version of hector_mapping called hector_localize that allows you to save maps you build and load them up later. You can then localize to these already created maps without actually running any mapping code making the entire process very lightweight.

Cheers,
Mark

### CODE REVIEW

**Comment by skohlbr** [comment]
Hi Mark, apologies for the huge delay. As you copied the hector_mapping code base to a new package, future changes always would have to be applied twice to the two packages. I´d therefore opt for merging changes with hector_mapping and making "localize only" available either by setting a parameter or by having a second executable. Hope I find the time in the next few weeks to have a closer look.

**Comment by mwd3** [comment]
Okay thanks.

Mark

**Comment by opaezosuna** [comment]
Hello,

I tried this code and it initially works for loading a map of arbitrary size. However if I load map1 of size w1 x h1, and after that I load map2 of size w2 x h2 having w1 != w2 or h1 != h2 this second time the map appears "garbled", as if somewhere, when resetting the hectorSlamProcessor pointer, the new sizes aren't updated correctly. And after initially loading a map of size w x h you can load correctly any map of size w x h.

Any pointers as to where to look to solve this issue?

Octavio

**Comment by StefanFabian** [comment]
Closed as @skohlbr concern was not addressed and it's a reasonable assumption that this won't happen.

**Comment by PhehJingJie** [comment]
@mwd3 @skohlbr @StefanFabian  Any possibility of merging this feature in the future?

**Comment by Martin-Oehler** [comment]
Hello jjbecomespheh,
this PR is orphaned and will not be merged until all issues are resolved. Please feel free to open a separate PR and continue on this work.
Best wishes.

**Pull request closed without merging**
