### PR TITLE
Eigen requires optimization to get good performance

### PR DESCRIPTION
**Pull request by k-okada**
c.f. https://github.com/tu-darmstadt-ros-pkg/hector_slam/issues/30

### CODE REVIEW

**Comment by meyerj** [comment]
Adding `-O3` unconditionally is not what we want, because cmake also adds optimization flag depending on the `CMAKE_BUILD_TYPE` setting and the result would depend on the ordering of definitions and cmake's compile flags.

I would suggest something like in [hector_pose_estimation_core/CMakeLists.txt:79](https://github.com/tu-darmstadt-ros-pkg/hector_localization/blob/catkin/hector_pose_estimation_core/CMakeLists.txt#L79). The resulting flags for `RelWithDebInfo` are `-O3 -g -DNDEBUG`, so they include `-O3`. `-DNDEBUG` also contributes to the [Eigen speed-up](https://eigen.tuxfamily.org/dox/TopicPreprocessorDirectives.html).

```
-- CMAKE_BUILD_TYPE:               RelWithDebInfo
-- CMAKE_CXX_FLAGS_RELEASE:        -O3 -DNDEBUG
-- CMAKE_CXX_FLAGS_RELWITHDEBINFO: -O3 -g -DNDEBUG
-- CMAKE_CXX_FLAGS_MINSIZEREL:     -Os -DNDEBUG
-- CMAKE_CXX_FLAGS_DEBUG:          -g
```

**Comment by k-okada** [comment]
That's interesting, did you test on my branch? it least my environment
(14.04, catkin_tools 0.4.2) this works fine.

## 

◉ Kei Okada

**Comment by k-okada** [comment]
any way I have created new PR which uses relWithDebugInfo,
https://github.com/tu-darmstadt-ros-pkg/hector_slam/pull/32
but I personally think even inf CMAKE_BUILD_TYPE is Debug, we should use
-O3 for Eigen Application, that's why the support NDEBUG option.

## 

◉ Kei Okada

**Comment by meyerj** [comment]
> That's interesting, did you test on my branch? it least my environment
> (14.04, catkin_tools 0.4.2) this works fine. 

Yes, your method works fine because `add_definitions()` apparently adds the flags after the `CMAKE_CXX_FLAGS_XXX` added by cmake itself, so they override the internal options:

``` cmake
CMakeLists.txt:
set(CMAKE_BUILD_TYPE RelWithDebInfo)
add_definitions(-O3)
add_library(...)

Compiler command line:
/usr/bin/c++   -DROSCONSOLE_BACKEND_LOG4CXX -DROS_PACKAGE_NAME=\"hector_pose_estimation_core\" -Dhector_pose_estimation_EXPORTS -O3 -g -DNDEBUG [...] -O2 [...]
```

But I am not sure if this behavior is well-defined and `add_definitions()` is actually [not meant for this purpose](https://cmake.org/cmake/help/latest/command/add_definitions.html).

> any way I have created new PR which uses relWithDebugInfo, #32
> but I personally think even inf CMAKE_BUILD_TYPE is Debug, we should use -O3 for Eigen Application, that's why the support NDEBUG option.

This is a valid argument, but the optimizations can make debugging really hard, even if `CMAKE_BUILD_TYPE` would be explicitly set to `Debug`. One reason why you would want this is to not slow down hector_slam while debugging other packages in the same workspace that has been built with build type `Debug`. But this is a build tool problem and should be solved by either splitting hector_slam off in a separate workspace or by setting the build type for specific packages only, which is IMHO not possible with catkin or catkin_tools for now.

@skohlbr, any thoughts?

**Comment by StefanFabian** [comment]
Not sure if it was possible back then but you can build packages without their dependencies using `--no-deps` which allows for building a single package using a different build type.
An alternative was always to set the type to debug manually in the package that is debugged.

**Pull request closed without merging**
